### ISSUE TITLE
Add ability to use custom registries

### ISSUE THREAD

**Issue by danielr1996** [danielr1996/docker-action-multitag#1]
Add a new input that allows to customize the repository, like this:
```
- name: Build
  uses: danielr1996/docker-action-multitag@1.0.0
  with:
    imagename: user/image
    dockeruser: ${{ secrets.DOCKER_USERNAME }}
    dockerpassword: ${{ secrets.DOCKER_PASSWORD }}
    dockerregistry: ....
```
